SET NAMES utf8mb4;

CREATE TABLE users (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(190) NOT NULL,
  password VARCHAR(255) NOT NULL,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  phone VARCHAR(30),
  role ENUM('ADMIN','AGENT','CLIENT') NOT NULL DEFAULT 'AGENT',
  status ENUM('ACTIVE','DISABLED','INVITED') NOT NULL DEFAULT 'ACTIVE',
  last_login_at DATETIME NULL,
  timezone VARCHAR(50) DEFAULT 'Europe/Paris',
  avatar_url VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by BIGINT NULL,
  updated_by BIGINT NULL,
  UNIQUE KEY uk_users_email (email),
  INDEX idx_users_role (role),
  INDEX idx_users_status (status),
  CONSTRAINT fk_users_created_by FOREIGN KEY (created_by) REFERENCES users(id),
  CONSTRAINT fk_users_updated_by FOREIGN KEY (updated_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE clients (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(190) NOT NULL,
  legal_name VARCHAR(190),
  siret VARCHAR(14),
  vat_number VARCHAR(32),
  contact_first_name VARCHAR(100),
  contact_last_name VARCHAR(100),
  contact_email VARCHAR(190),
  contact_phone VARCHAR(30),
  billing_email VARCHAR(190),
  technical_email VARCHAR(190),
  website_url VARCHAR(255),
  address_line1 VARCHAR(190),
  address_line2 VARCHAR(190),
  postal_code VARCHAR(20),
  city VARCHAR(100),
  state VARCHAR(100),
  country_code CHAR(2) DEFAULT 'FR',
  currency_code CHAR(3) DEFAULT 'EUR',
  timezone VARCHAR(50) DEFAULT 'Europe/Paris',
  status ENUM('ACTIVE','INACTIVE','LEAD') NOT NULL DEFAULT 'ACTIVE',
  notes TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by BIGINT NULL,
  updated_by BIGINT NULL,
  UNIQUE KEY uk_clients_name (name),
  UNIQUE KEY uk_clients_siret (siret),
  UNIQUE KEY uk_clients_vat (vat_number),
  INDEX idx_clients_status (status),
  CONSTRAINT fk_clients_created_by FOREIGN KEY (created_by) REFERENCES users(id),
  CONSTRAINT fk_clients_updated_by FOREIGN KEY (updated_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE sites (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  client_id BIGINT NOT NULL,
  name VARCHAR(190) NOT NULL,
  url VARCHAR(255) NOT NULL,
  environment ENUM('PROD','STAGING','DEV') NOT NULL DEFAULT 'PROD',
  type ENUM('WEBSITE','SHOP','API','APP') NOT NULL DEFAULT 'WEBSITE',
  cms ENUM('WORDPRESS','SHOPIFY','DRUPAL','PRESTASHOP','CUSTOM','OTHER') NOT NULL DEFAULT 'CUSTOM',
  repo_url VARCHAR(255),
  prod_url VARCHAR(255),
  staging_url VARCHAR(255),
  hosting_provider VARCHAR(100),
  hosting_plan VARCHAR(100),
  server_ip VARCHAR(45),
  php_version VARCHAR(20),
  node_version VARCHAR(20),
  mysql_version VARCHAR(20),
  ssl_status ENUM('UNKNOWN','VALID','EXPIRED','NOT_INSTALLED') NOT NULL DEFAULT 'UNKNOWN',
  analytics_id VARCHAR(100),
  gt_id VARCHAR(50),
  sentry_dsn VARCHAR(255),
  maintenance_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  maintenance_email VARCHAR(190),
  last_maintenance_at DATETIME NULL,
  next_maintenance_at DATETIME NULL,
  last_backup_at DATETIME NULL,
  status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  notes TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by BIGINT NULL,
  updated_by BIGINT NULL,
  UNIQUE KEY uk_sites_client_name (client_id, name),
  UNIQUE KEY uk_sites_url (url),
  INDEX idx_sites_client (client_id),
  INDEX idx_sites_status (status),
  CONSTRAINT fk_sites_client FOREIGN KEY (client_id) REFERENCES clients(id),
  CONSTRAINT fk_sites_created_by FOREIGN KEY (created_by) REFERENCES users(id),
  CONSTRAINT fk_sites_updated_by FOREIGN KEY (updated_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
